{
  AEGitRepository © 2026 by Akos Eigler is licensed under CC BY 4.0.
  To view a copy of this license, visit http://creativecommons.org/licenses/by/4.0/

  This license requires that reusers give credit to the creator. It allows reusers to distribute, remix, adapt,
  and build upon the material in any medium or format, even for commercial purposes.
}

Unit AE.GitRepository.TypeDef;

Interface

Uses libgit2, System.Generics.Collections;

Type
  TAEGitErrorCode = (
    geOk = 0,                 // GIT_OK
    geError = -1,             // GIT_ERROR
    geNotFound = -3,          // GIT_ENOTFOUND
    geObjectExists = -4,      // GIT_EEXISTS
    geAmbiguous = -5,         // GIT_EAMBIGUOUS
    geBufTooSmall = -6,       // GIT_EBUFS
    geUser = -7,              // GIT_EUSER
    geBareRepo = -8,          // GIT_EBAREREPO
    geUnbornBranch = -9,      // GIT_EUNBORNBRANCH
    geUnmerged = -10,         // GIT_EUNMERGED
    geNonFastForward = -11,   // GIT_ENONFASTFORWARD
    geInvalidSpec = -12,      // GIT_EINVALIDSPEC
    geConflict = -13,         // GIT_ECONFLICT
    geLocked = -14,           // GIT_ELOCKED
    geModified = -15,         // GIT_EMODIFIED
    geAuth = -16,             // GIT_EAUTH
    geCertificate = -17,      // GIT_ECERTIFICATE
    geAlreadyApplied = -18,   // GIT_EAPPLIED
    gePeel = -19,             // GIT_EPEEL
    geEOF = -20,              // GIT_EEOF
    geInvalid = -21,          // GIT_EINVALID
    geUncommitted = -22,      // GIT_EUNCOMMITTED
    geDirectory = -23,        // GIT_EDIRECTORY
    geMergeConflict = -24,    // GIT_EMERGECONFLICT
    gePassthrough = -30,      // GIT_PASSTHROUGH
    geIterationOver = -31,    // GIT_ITEROVER
    geRetry = -32,            // GIT_RETRY
    geHashMismatch = -33,     // GIT_EMISMATCH
    geIndexDirty = -34,       // GIT_EINDEXDIRTY
    geApplyFailed = -35,      // GIT_EAPPLYFAIL
    geWrongOwner = -36,       // GIT_EOWNER
    geTimeout = -37,          // GIT_TIMEOUT
    geUnchanged = -38,        // GIT_EUNCHANGED
    geNotSupported = -39,     // GIT_ENOTSUPPORTED
    geReadOnly = -40,         // GIT_EREADONLY
    geUnknown = -999
  );

  TAEGitAuthType = (
    gaUserPassPlainText = 1,   // GIT_CREDENTIAL_USERPASS_PLAINTEXT
    gaSshKey = 2,              // GIT_CREDENTIAL_SSH_KEY
    gaSshCustom = 4,           // GIT_CREDENTIAL_SSH_CUSTOM
    gaDefault = 8,             // GIT_CREDENTIAL_DEFAULT
    gaSshInteractive = 16,     // GIT_CREDENTIAL_SSH_INTERACTIVE
    gaUsername = 32,           // GIT_CREDENTIAL_USERNAME
    gaSshMemory = 64           // GIT_CREDENTIAL_SSH_MEMORY
  );

  TAEGitAuthTypes = Set Of TAEGitAuthType;

  TAEGitLibCallLogEvent = Procedure(Const inSender: TObject; Const inMethod: String; Const inErrorCode: TAEGitErrorCode) Of Object;

  TGitLibAuthCallback = Function(outGitCredential: PPgit_credential; inURL, inUserName: PAnsiChar; inAllowedTypes: TAEGitAuthTypes): Integer Of Object;

  TAEGitFileStatus = ( gfsCurrent, gfsStagedNew, gfsStagedModified, gfsStagedDeleted, gfsStagedRenamed, gfsStagedTypeChange,
    gfsNew, gfsModified, gfsDeleted, gfsTypeChange, gfsRenamed, gfsUnreadable, gfsIgnored, gfsConflicted );

  TAEGitStashList = Class(TList<String>);

  PAEGitStashList = ^TAEGitStashList;

  TAEGitChangedFileList = Class(TDictionary<String, TArray<TAEGitFileStatus>>);

  TAEGitBranchType = ( gbLocal, gbRemote, gbAll );

Const
  AEGITFILESTATUSSTR: Array[TAEGitFileStatus] Of String = ('Current', 'New', 'Modified', 'Deleted', 'Renamed',
    'Type change', 'New', 'Modified', 'Deleted', 'Type change', 'Renamed', 'Unreadable', 'Ignored', 'Conflicted');

Function AEGitErrorDescription(Const inErrorCode: TAEGitErrorCode): String;

Implementation

Function AEGitErrorDescription(Const inErrorCode: TAEGitErrorCode): String;
Begin
  Case inErrorCode Of
    geOk:
      Result := 'Success';
    geError:
      Result := 'Generic error';
    geNotFound:
      Result := 'Requested object could not be found';
    geObjectExists:
      Result := 'Object exists preventing operation';
    geAmbiguous:
      Result := 'More than one object matches';
    geBufTooSmall:
      Result := 'Output buffer too short to hold data';
    geUser:
      Result := 'Generated by user callback';
    geBareRepo:
      Result := 'Operation not allowed on bare repository';
    geUnbornBranch:
      Result := 'HEAD refers to a branch with no commits';
    geUnmerged:
      Result := 'Merge in progress prevented operation';
    geNonFastForward:
      Result := 'Reference was not fast-forwardable';
    geInvalidSpec:
      Result := 'Name/ref specification is invalid';
    geConflict:
      Result := 'Checkout conflicts prevented operation';
    geLocked:
      Result := 'Lock file prevented operation';
    geModified:
      Result := 'Reference value does not match expected';
    geAuth:
      Result := 'Authentication error';
    geCertificate:
      Result := 'Server certificate is invalid';
    geAlreadyApplied:
      Result := 'Patch or merge has already been applied';
    gePeel:
      Result := 'Requested peel operation is not possible';
    geEOF:
      Result := 'Unexpected end of file';
    geInvalid:
      Result := 'Invalid operation or input';
    geUncommitted:
      Result := 'Uncommitted changes prevented operation';
    geDirectory:
      Result := 'Operation is not valid for a directory';
    geMergeConflict:
      Result := 'Merge conflict exists and cannot continue';
    gePassthrough:
      Result := 'User-configured callback refused to act';
    geIterationOver:
      Result := 'End of iteration';
    geRetry:
      Result := 'Internal retry requested';
    geHashMismatch:
      Result := 'Object hash mismatch';
    geIndexDirty:
      Result := 'Unsaved index changes would be overwritten';
    geApplyFailed:
      Result := 'Patch application failed';
    geWrongOwner:
      Result := 'Object is not owned by the current user';
    geTimeout:
      Result := 'Operation timed out';
    geUnchanged:
      Result := 'There were no changes';
    geNotSupported:
      Result := 'Option is not supported';
    geReadOnly:
      Result := 'Subject is read-only';
    Else // geUnknown
      Result := 'Unknown libgit2 error';
  End;
End;

End.
